# Enunciado del ejercicio 1 de sistemas lineales

Resolver las ecuaciones Ax = b utilizando la descomposición de Doolittle para A. Resolver el sistema utilizando la descomposición LU obtenida para diversos b.

In [1]:
import numpy as np
A = np.array([
    [1, 2, 4, 3, 5],
    [3, 5, 3, 1, 2],
    [1, 4, 4, 2, 1],
    [4, 1, 2, 5, 3],
    [5, 2, 1, 4, 1]])

In [2]:
dimension = np.shape(A)[0]
L = np.identity(dimension)
L

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

# Chequear si la matriz es diagonalmente dominante

Aunque la matriz sólo tiene enteros positivos, agrego el cálculo del valor absoluto por si después probamos con otra matriz.

In [3]:
def isDiagDom(A):
    
    # Aunque la matriz del problema sólo tiene enteros
    # positivos, generalizo para matrices con otras
    # características
    
    diagA = np.absolute(np.multiply(A, L))
    fueraDiagA = np.absolute(A - diagA)
    
    sumDiagA = np.sum(diagA)
    sumFueraDiagA = np.sum(fueraDiagA)
    
    print("diagonal de A: \n", diagA)
    print("----------------------------------------")
    print("resto de A: \n", fueraDiagA)
    print("----------------------------------------")
    print("suma diagonal: ", sumDiagA)
    print("suma del resto de los elementos: ", sumFueraDiagA)
    print("----------------------------------------")
    
    if sumDiagA < sumFueraDiagA:
        print("La matriz NO es diagonalmente dominante, ¡seguí participando!")
        return False
    else:
        print("Todo bien, seguí adelante!")
        return True

In [4]:
isDiagDom(A)

diagonal de A: 
 [[ 1.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.]
 [ 0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  1.]]
----------------------------------------
resto de A: 
 [[ 0.  2.  4.  3.  5.]
 [ 3.  0.  3.  1.  2.]
 [ 1.  4.  0.  2.  1.]
 [ 4.  1.  2.  0.  3.]
 [ 5.  2.  1.  4.  0.]]
----------------------------------------
suma diagonal:  16.0
suma del resto de los elementos:  53.0
----------------------------------------
La matriz NO es diagonalmente dominante, ¡seguí participando!


False

# Convirtiendo la matriz en diagonalmente dominante

Por simple inspección muevo las filas para que en la diagonal queden los valores más grandes. Llamo U1 a la nueva matriz.

In [5]:
U1 = A.copy()
U1[0, ::] = A[4, ::]
U1[4, ::] = A[0, ::]
U1

array([[5, 2, 1, 4, 1],
       [3, 5, 3, 1, 2],
       [1, 4, 4, 2, 1],
       [4, 1, 2, 5, 3],
       [1, 2, 4, 3, 5]])

In [6]:
isDiagDom(U1)

diagonal de A: 
 [[ 5.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.]
 [ 0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  5.]]
----------------------------------------
resto de A: 
 [[ 0.  2.  1.  4.  1.]
 [ 3.  0.  3.  1.  2.]
 [ 1.  4.  0.  2.  1.]
 [ 4.  1.  2.  0.  3.]
 [ 1.  2.  4.  3.  0.]]
----------------------------------------
suma diagonal:  24.0
suma del resto de los elementos:  45.0
----------------------------------------
La matriz NO es diagonalmente dominante, ¡seguí participando!


False

**Unicamente con permutaciones no veo cómo se puede convertir la matriz en diagonalmente dominante, seguro me estoy perdiendo de algo.**

# Inicio del proceso

Igual armo el procedimiento...

**Observación**: en la matriz U2 voy a ir guardando los resultados de operar con U1, así puedo correr múltiples veces las celdas del notebook sin tener que reiniciar el kernel para resetear las matrices.

In [7]:
U2 = U1.copy()
U2

array([[5, 2, 1, 4, 1],
       [3, 5, 3, 1, 2],
       [1, 4, 4, 2, 1],
       [4, 1, 2, 5, 3],
       [1, 2, 4, 3, 5]])

# Poniendo a cero la columna 0

**Los L[i,0] están calculados analíticamente, aunque habría que chequearlo...**.

$$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} & a_{03} & a_{04} \\
a_{10} & a_{11} & a_{12} & a_{13} & a_{14} \\
a_{20} & a_{21} & a_{22} & a_{23} & a_{24} \\
a_{30} & a_{31} & a_{32} & a_{33} & a_{34} \\
a_{40} & a_{41} & a_{42} & a_{43} & a_{44} \\
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
L_{10} & 1 & 0 & 0 & 0 \\
L_{20} & L_{21} & 1 & 0 & 0 \\
L_{30} & L_{31} & L_{32} & 1 & 0 \\
L_{40} & L_{41} & L_{42} & L_{43} & 1
\end{bmatrix} \cdot
\begin{bmatrix}
U_{00} & U_{01} & U_{02} & U_{03} & U_{04} \\
0 & U_{11} & U_{12} & U_{13} & U_{14} \\
0 & 0 & U_{22} & U_{23} & U_{24} \\
0 & 0 & 0 & U_{33} & U_{34} \\
0 & 0 & 0 & 0 & U_{44} \\
\end{bmatrix}
$$

De ahí se despejan los $L_{10}$, $L_{20}$, etc.

$$ 
a_{00} = 1 \cdot U_{00} \\
a_{10} =  L_{10} \cdot U_{00} \\
\dots \\
a_{31} = L_{30}U_{01} + L_{31}U_{11} \\
a_{32} = L_{30}U_{02} + L_{31}U_{12} + L_{32}U_{22} \\
\dots \\
a_{43} = L_{40}U_{03} + L_{41}U_{13} + L_{42}U_{23} + L_{43}U_{33} \\
\dots
$$

### Inicio de los cálculos

In [8]:
n = U1[1,0] / U1[0,0]
U2[1, ::] = U1[1, ::] - n * U1[0, ::]

L[1,0] = U1[1,0] / U2[0,0]

print(L[1,0])
print(n)

0.6
0.6


In [9]:
n = U1[2,0] / U1[0,0]
U2[2, ::] = U1[2, ::] - n * U1[0, ::]

L[2,0] = U1[2,0] / U2[0,0]

print(L[2,0])
print(n)

0.2
0.2


In [10]:
n = U1[3,0] / U1[0,0]
U2[3, ::] = U1[3, ::] - n * U1[0, ::]

L[3,0] = U1[3,0] / U2[0,0]

print(L[3,0])
print(n)

0.8
0.8


In [11]:
n = U1[4,0] / U1[0,0]
U2[4, ::] = U1[4, ::] - n * U1[0, ::]

L[4,0] = U1[4,0] / U2[0,0]

print(L[4,0])
print(n)

0.2
0.2


In [12]:
U2

array([[ 5,  2,  1,  4,  1],
       [ 0,  3,  2, -1,  1],
       [ 0,  3,  3,  1,  0],
       [ 0,  0,  1,  1,  2],
       [ 0,  1,  3,  2,  4]])

## Síntesis del proceso de poner a cero la columna 0

Todos los pasos anteriores destinados a igualar a cero los elementos debajo de U[0,0] se pueden sintetizar así:

In [13]:
# U2 = U1.copy()
# for i in range(1, 5):
#    n = U1[i,0] / U1[0,0]
#    U2[i, ::] = U1[i, ::] - n * U1[0, ::]
#    L[i,0] = U1[i,0] / U2[0,0]

# Poniendo a cero la columna 1

In [14]:
U3 = U2.copy()

n = U2[2,1] / U2[1,1]
U3[2, ::] = U2[2, ::] - n * U2[1, ::]

L[2,1] = (U1[2,1] - L[2,0] * U3[0,1]) / U3[1,1]

print("Acá ya hay diferencias entre L[i,1] y n")
print(L[2,1])
print(n)
print("------------")
print(U1[2,1])
print(L[2,0] * U3[0,1])
print(U3[1,1])


Acá ya hay diferencias entre L[i,1] y n
1.2
1.0
------------
4
0.4
3


In [15]:
n = U2[3,1] / U2[1,1]
U3[3, ::] = U2[3, ::] - n * U2[1, ::]

L[3,1] = (U1[3,1] - L[3,0] * U3[0,1]) / U3[1,1]
L[3,1]

print(L[3,1])
print(n)

-0.2
0.0


In [16]:
n = U2[4,1] / U2[1,1]
U3[4, ::] = U2[4, ::] - n * U2[1, ::]

L[4,1] = (U1[4,1] - L[4,0] * U3[0,1]) / U3[1,1]

print(L[4,1])
print(n)

0.533333333333
0.333333333333


In [23]:
U3

array([[ 5,  2,  1,  4,  1],
       [ 0,  3,  2, -1,  1],
       [ 0,  0,  1,  2, -1],
       [ 0,  0,  1,  1,  2],
       [ 0,  0,  2,  2,  3]])

# Poniendo a cero la columna 2

In [17]:
U4 = U3.copy()

n = U3[3,2] / U3[2,2]
U4[3, ::] = U3[3, ::] - n * U3[2, ::]

L[3,2] = (U1[3,2] - L[3,0] * U4[0,2] - L[3,1] * U4[1,2]) / U4[2,2]

print(L[3,2])
print(n)

1.6
1.0


In [18]:
n = U3[4,2] / U3[2,2]
U4[4, ::] = U3[4, ::] - n * U3[2, ::]

L[4,2] = (U1[4,2] - L[4,0] * U4[0,2] - L[4,1] * U4[1,2]) / U4[2,2]

print(L[4,2])
print(n)

2.73333333333
2.0


In [24]:
U4

array([[ 5,  2,  1,  4,  1],
       [ 0,  3,  2, -1,  1],
       [ 0,  0,  1,  2, -1],
       [ 0,  0,  0, -1,  3],
       [ 0,  0,  0, -2,  5]])

# Poniendo a cero la columna 3

In [19]:
U5 = U4.copy()

n = U4[4,3] / U4[3,3]
U5[4, ::] = U4[4, ::] - n * U4[3, ::]

L[4,3] = (U1[4,3] - L[4,0] * U5[0,3] - L[4,1] * U5[1,3] - L[4,2] * U5[2,3]) / U5[3,3]

print(L[4,3])
print(n)

2.73333333333
2.0


In [25]:
U5

array([[ 5,  2,  1,  4,  1],
       [ 0,  3,  2, -1,  1],
       [ 0,  0,  1,  2, -1],
       [ 0,  0,  0, -1,  3],
       [ 0,  0,  0,  0, -1]])

# Verificación (¡no se verifica!)

In [20]:
# para mostrar las matrices sin notación científica
np.set_printoptions(suppress=True, precision=3) 

print("matriz A\n", U1)
print()
print("L * U\n", np.dot(L,U5))
print()
print("L\n", L)
print()
print("U\n", U5)


matriz A
 [[5 2 1 4 1]
 [3 5 3 1 2]
 [1 4 4 2 1]
 [4 1 2 5 3]
 [1 2 4 3 5]]

L * U
 [[ 5.   2.   1.   4.   1. ]
 [ 3.   4.2  2.6  1.4  1.6]
 [ 1.   4.   3.6  1.6  0.4]
 [ 4.   1.   2.   5.6  2. ]
 [ 1.   2.   4.   3.   5.2]]

L
 [[ 1.     0.     0.     0.     0.   ]
 [ 0.6    1.     0.     0.     0.   ]
 [ 0.2    1.2    1.     0.     0.   ]
 [ 0.8   -0.2    1.6    1.     0.   ]
 [ 0.2    0.533  2.733  2.733  1.   ]]

U
 [[ 5  2  1  4  1]
 [ 0  3  2 -1  1]
 [ 0  0  1  2 -1]
 [ 0  0  0 -1  3]
 [ 0  0  0  0 -1]]


# Cálculo de L y U con Scipy

In [21]:
import scipy.linalg as la

# para mostrar las matrices sin notación científica
np.set_printoptions(suppress=True, precision=5) 

p0, L0, U0 = la.lu(U1)

# Verificación

In [22]:
print("matriz A\n", U1)
print()
print("L * U\n", np.dot(L0,U0))
print()
print("L\n", L0)
print()
print("U\n", U0)
print()
print("permutaciones\n", p0)

matriz A
 [[5 2 1 4 1]
 [3 5 3 1 2]
 [1 4 4 2 1]
 [4 1 2 5 3]
 [1 2 4 3 5]]

L * U
 [[ 5.  2.  1.  4.  1.]
 [ 3.  5.  3.  1.  2.]
 [ 1.  2.  4.  3.  5.]
 [ 1.  4.  4.  2.  1.]
 [ 4.  1.  2.  5.  3.]]

L
 [[ 1.       0.       0.       0.       0.     ]
 [ 0.6      1.       0.       0.       0.     ]
 [ 0.2      0.42105  1.       0.       0.     ]
 [ 0.2      0.94737  0.54717  1.       0.     ]
 [ 0.8     -0.15789  0.56604 -0.       1.     ]]

U
 [[ 5.       2.       1.       4.       1.     ]
 [ 0.       3.8      2.4     -1.4      1.4    ]
 [ 0.       0.       2.78947  2.78947  4.21053]
 [ 0.       0.       0.       1.      -2.83019]
 [ 0.       0.       0.       0.       0.03774]]

permutaciones
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.]]
