# Sistemas lineales

## Ejercicio 1: Descomposición de Doolittle

Resolver las ecuaciones Ax = b utilizando la descomposición de Doolittle para A. Resolver el sistema utilizando la descomposición LU obtenida para diversos b.

In [1]:
import numpy as np

A = np.array([
    [1, 2, 4, 3, 5],
    [3, 5, 3, 1, 2],
    [1, 4, 4, 2, 1],
    [4, 1, 2, 5, 3], 
    [5, 2, 1, 4, 1]])

# Armado de las matrices L y U (aún vacías)

In [2]:
dim = np.shape(A)[0]

L = np.identity(dim)
U = np.zeros((dim,dim))

print("Matriz L.")
print("Triangular inferior, y la diagonal rellena con unos (1):")
print(L)
print()
print("Matriz U.")
print("Triangular superior:")
print(U)

Matriz L.
Triangular inferior, y la diagonal rellena con unos (1):
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]

Matriz U.
Triangular superior:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


# Funciones para hallar los elementos $L_{ij}$ y $U_{ij}$

In [3]:
def Lij(A, L, U, i, j):
    indiceSum = np.arange(0, j, 1)
    ac = 0
    for k in indiceSum:
        ac = ac + L[i,k] * U[k,j]
    return (A[i,j] - ac) / U[j,j]

In [4]:
def Uij(A, L, U, i, j):
    indiceSum = np.arange(0, i, 1)
    ac = 0
    for k in indiceSum:
        ac = ac + L[i,k] * U[k,j]
    return A[i,j] - ac

# Hallamos todos los elementos no nulos de $L$ y $U$

Partimos del elemento 0,0 y barremos la primera columna, luego la segunda, etc.

In [5]:
for j in range(dim):
    for i in range(dim):
        if j>=i:
            U[i,j] = Uij(A, L, U, i, j)
        else:
            L[i,j] = Lij(A, L, U, i, j)

# Verificación

Se debe cumplir que $L \cdot U - A = 0$

In [6]:
def verificador(matriz1, matriz2):
    """verifica que los elementos de matriz1 y matriz2 sean casi iguales
    (la tolerancia está dada por defecto en np.allclose, pero se podría cambiar)
    """
    
    sonIguales = np.allclose(matriz1, matriz2)
    if sonIguales:
        print("¡Verificación OK!")
    else:
        print("¡Hubo un error en el cálculo!")

In [7]:
verificador(np.dot(L,U), A)

¡Verificación OK!


# Funciones para hallar los elementos de $y$ y $x$

In [8]:
def y_n(L, b, y, n):
    indiceSum = np.arange(0, n, 1)
    ac = 0
    for k in indiceSum:
        ac = ac + L[n,k] * y[k]
    return b[n] - ac

In [9]:
def x_n(U, y, x, n):
    n_max = y.size
    indiceSum = np.arange(n, n_max, 1)
    ac = 0
    for k in indiceSum:
        ac = ac + U[n,k] * x[k]
    return (y[n] - ac) / U[n,n]

# Solución particular, para un vector $b$:

In [10]:
b = np.array([5, 6, 7, 8, 9])
b

array([5, 6, 7, 8, 9])

## Cálculo del vector $y$

In [11]:
y = np.zeros(b.size)

for k in range(b.size):
    y[k] = y_n(L, b, y, k)

## Verificación

Se debe cumplir que $L \cdot y = b$

In [12]:
verificador(np.dot(L, y), b)

¡Verificación OK!


# Cálculo final: obtención del vector $x$

In [13]:
x = np.zeros(b.size)
for k in range(b.size-1, -1, -1):
    x[k] = x_n(U, y, x, k)
    
print("el vector solución es:", x)

el vector solución es: [ 59.5 -67.5  87.  -55.  -20.5]


## Verificación

Se debe cumplir que $U \cdot x = y$

In [14]:
verificador(np.dot(U, x), y)

¡Verificación OK!


También se debe cumplir que $A \cdot x = b$:

In [15]:
verificador(np.dot(A, x), b)

¡Verificación OK!
